# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200115_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=11, unique=True, verbose_name='书名'),
        ),
    ]
