# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
