# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('desc', models.CharField(max_length=50, verbose_name='个人描述')),
            ],
        ),
    ]
